---
title: "GIS-Shiny"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(ggmap)
library(tidyverse)
library(shiny)
library(DT)
library(forcats)

df1<- read.csv("C:/Users/TaoWa/Desktop/by_client_with_sequences.csv")

dff<-
  df1%>%
  rename(parents_college=q80)%>%
  mutate(parents_college=fct_recode(parents_college, 
                                    "yes" = "1", 
                                    "no" = "2", 
                                    "missing" = ".a", 
                                    "multiple" = ".b" ))%>%
  rename(gender=q72)%>%
  mutate(gender=fct_recode(gender, 
                           "female" = "1", 
                           "male" = "2", 
                           "uncertain" = "3",
                           "missing" = ".a", 
                           "multiple" = ".b" ))%>%
  rename(coop=q79)%>%
  mutate(coop=fct_recode(coop,
                         "yes" = "1", 
                         "no" = "2", 
                         "unknown" = "3",
                         "missing" = ".a", 
                         "multiple" = ".b"  ))%>%
  mutate(useful_skills=fct_recode(q13s,
                                  "Very Dissatisfied"="1",
                                  "Dissatisfied"="2",
                                  "Neither Satisfied nor Dissatisfied"="3",
                                  "Satisfied"="4",
                                  "Very Satisfied"="5",
                                  "missing" = ".a", 
                                  "multiple" = ".b"))%>%
  mutate(q13s=fct_recode(q13s,
                         "Very Dissatisfied"="1",
                         "Dissatisfied"="2",
                         "Neither Satisfied nor Dissatisfied"="3",
                         "Satisfied"="4",
                         "Very Satisfied"="5",
                         "missing" = ".a", 
                         "multiple" = ".b")) %>%
  mutate(q24s=fct_recode(q24s,
                         "Very Dissatisfied"="1",
                         "Dissatisfied"="2",
                         "Neither Satisfied nor Dissatisfied"="3",
                         "Satisfied"="4",
                         "Very Satisfied"="5",
                         "missing" = ".a", 
                         "multiple" = ".b"))%>%
  mutate(q39s=fct_recode(q39s,
                         "Very Dissatisfied"="1",
                         "Dissatisfied"="2",
                         "Neither Satisfied nor Dissatisfied"="3",
                         "Satisfied"="4",
                         "Very Satisfied"="5",
                         "missing" = ".a", 
                         "multiple" = ".b"))%>%
  mutate(q49s=fct_recode(q49s,
                         "Very Dissatisfied"="1",
                         "Dissatisfied"="2",
                         "Neither Satisfied nor Dissatisfied"="3",
                         "Satisfied"="4",
                         "Very Satisfied"="5",
                         "missing" = ".a", 
                         "multiple" = ".b"))



## transfer postal type from integer to character, so that we can use geocode
dff$postal<-as.character(dff$postal)

## group the data set by postcode, and count the number of each postcode
loglat <-
  dff %>%
  group_by(postal) %>%
  summarise(count= n())

## delete the 44th observatrion with na in postal
loglat <- loglat[-44,]

## for testing TODO remove the line below 
# loglat <- sample_n(loglat, 3)

## find the log and lat of each post code
loglat$cologlat<- geocode(loglat$postal)

```

Column {data-width=200}
-----------------------------------------------------------------------

### selection bar

```{r selectbar}
selectInput("var1", 
                              label = "year selection",
                              choices = c("13/14", "14/15",
                                          "15/16"),
                              selected = "13/14")

selectInput("var2",
                    label= "trade code",
                    choices = c("309A","310S","306A","403A","310T","620C","433A","313A","308A","415A", "all trades"),
                    selected = "all trades")
```

Column {data-width=800}
-----------------------------------------------------------------------

### GIS for client numbers by year

```{r}
renderLeaflet({
    
    ## plot_data by year
    if(input$var1 == "13/14") {
      plot_data <- 
        dff %>%
        filter(year == "13/14")
    } 
    else if (input$var1 == "14/15") {
      plot_data <- 
        dff %>%
        filter(year == "14/15")
    }
    else {
      plot_data <- 
        dff %>%
        filter(year == "15/16")
    }
  
  # (input$var2)
  # plot_data by top 10 trades
   # if (TRUE) {
   if ( input$var2 == "all trades") {
     plot_data <- plot_data
   }
   else {
    plot_data <-
      plot_data %>%
      filter(trade == input$var2)
   }



  
    fulldata <- inner_join( plot_data, loglat, by = "postal")
 
    
     leaflet(fulldata) %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(~cologlat[,1], ~cologlat[,2], popup = ~postal, label = ~postal, clusterOptions = markerClusterOptions() )  
})
```


